# For details of the below fields, please refer CUSTOMISE.md
PROJECT_NAME: asha_bot
CHAT_APPLICATION: whatsapp
API_ACTIVATED: true
USERS : ['Asha']
EXPERTS:
  ANM: 'Clinical'
ESCALATION:
  Teacher: 
    name: 'Senior ANM'
    whatsapp_id: '919876543210'

USER_PROMPT : 'You are Asha bot. Your purpose is to help Asha workers with any queries that they might have while doing their Asha duties.'

RECREATE_EMBEDDINGS: false
SHOW_CITATIONS: true
SEND_POLL: false
SUGGEST_NEXT_QUESTIONS: true
MAX_CONVERSATION_LENGTH: 5
GLOB_SUFFIX: '*.txt'

ESCALATE_MULTIPLE: true
NUM_ESCALATE_EXPERTS: 5
MAX_ESCALATION_EXPERTS: 15
MIN_CONSENSUS_RESPONSES: 5

SEND_FEEDBACK_POLL: true
FEEDBACK_POLL_PROBABILITY: 0.2

WELCOME_MESSAGES:
  USERS:
    - 'Hi! I am Asha Bot. I can help you with any queries that you have regarding your Asha duties.'
  EXPERTS:
    - 'Hi! I am Asha Bot. Thank you for volunteering.'
SUGGESTION_QUESTIONS:
  - 'What are the side effects of Antara injection?'
  - 'Tell me about malnutrition.'
  - 'How many iron tablets should be taken during pregnancy?'

COSMOS_DB_NAME: llm-bot-database
COSMOS_LOGGING_COLLECTION: logs
AZURE_BLOB_CONTAINER_NAME: asha-bot

#NEW_DB
COSMOS_USER_COLLECTION: users
COSMOS_RELATIONS_COLLECTION: relations
COSMOS_USER_CONV_COLLECTION: user_conversations
COSMOS_BOT_CONV_COLLECTION: bot_conversations
COSMOS_EXPERT_CONV_COLLECTION: expert_conversations

SPREADSHEET_ID: abcd
SHEET_LINK: https://docs.google.com/spreadsheets/d/abcd/edit?usp=sharing
EMAIL_ID: abcd@gmail.com
EMAIL_PASS: abcd
EMAIL_LIST: ["test@microsoft.com"]